apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: db
  name: db
  namespace: bertapp
spec:
  replicas: 2 #???
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: db-api
          image: gcr.io/data-engineering2020/dbapi:0.0.1
          ports:
            - containerPort: 5000
              protocol: TCP
          env:
            - name: PSQL_HOST
              value: "34.122.90.27"
            - name: PSQL_PORT
              value: "5432"
            - name: PSQL_USR
              value: "postgres"
            - name: PSQL_PASS
              value: "DE2020_group6"
            - name: PSQL_DB
              value: "de2020"

