apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: db
  name: db
  namespace: bertapp
spec:
  replicas: 2 #in case one pod fails, ensures kubernetes self healing
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: db-api
          image: gcr.io/data-engineering2020/dbapi:0.0.1 #the adress to the dbapi image that we pushed to the google image repository
          ports:
            - containerPort: 5000 #port exposed as in dockerfile
              protocol: TCP
          env: #setting the environment variables that were defined in the docker file of dbapi
            - name: PSQL_HOST
              value: "34.122.90.27" #this ip should be changed before deploying the pod to the external ip that is assigned to postgreSQL by the loadbalancer
            - name: PSQL_PORT
              value: "5432" #standard port for postgreSQL
            - name: PSQL_USR
              value: "postgres" #standard user for postgreSQL
            - name: PSQL_PASS
              value: "DE2020_group6"
            - name: PSQL_DB
              value: "de2020" #database that stores the training data

