apiVersion: v1
kind: Service
metadata:
  name: db-service
  labels:
    app: db
  namespace: bertapp
spec:
  type: LoadBalancer
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: db