apiVersion: v1
kind: Service
metadata:
  name: db-service
  labels:
    app: db
  namespace: bertapp
spec:
  type: LoadBalancer #using loadbalancer in order to assign external ip adress for external connection
  ports:
    - port: 5000 #making sure that we can acces the dbapi, if we need to manually edit our training data database, via the port 5000 
      targetPort: 5000 #port was specified in db-deployment.yaml
  selector:
    app: db
