apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
  namespace: bertapp
spec:
  type: NodePort #LoadBalancer?
  ports:
    - port: 5432 #klopt dit? @job
  selector:
    app: postgres

#kubectl create -f postgres-service.yaml