apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-volume
  labels:
    type: local
    app: postgres
  namespace: bertapp
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi #hoeveel nodig?
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data" #klopt dit @job
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
  labels:
    app: postgres
  namespace: bertapp
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi #hoeveel nodig?
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-model-repo
  namespace: bertapp
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi #hoeveel nodig?
  storageClassName: manual

#kubectl create -f postgres-storage.yaml