apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: bert_app
spec:
  replicas: 1 #hoevel pods nodig?
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data #klopt dit? @job
              name: de2020
      volumes:
        - name: de2020
          persistentVolumeClaim:
            claimName: postgres-pv-claim

#kubectl create -f postgres-deployment.yaml
