apiVersion: v1
kind: Service
metadata:
  name: predict-service
  labels:
    app: predict
  namespace: bertapp
spec:
  type: LoadBalancer #using loadbalancer in order to allow external connections
  ports:
    - port: 5002 #making sure that we can acces the dbapi, if we need to manually edit our training data database, via the port 5000
      targetPort: 5000
  selector:
    app: predict
