apiVersion: v1
kind: Service
metadata:
  name: predict-service
  labels:
    app: predict
  namespace: bert_app
spec:
  type: LoadBalancer
  ports:
    - port: 5002
      targetPort: 5000
  selector:
    app: predict