apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: predict
  name: predict
  namespace: bertapp
spec:
  replicas: 2 #in case one pod fails, ensures kubernetes self healing
  selector:
    matchLabels:
      app: predict
  template:
    metadata:
      labels:
        app: predict
    spec:
      containers:
        - name: predict-api
          image: gcr.io/data-engineering2020/predict:0.0.1 #the adress of the image of the predict api that we pushed to the google image repository 
          volumeMounts:
            - mountPath: /usr/src/assignment1/models #the path that is used by the predict api to retrieve the model that was trained
              name: model-repo
          ports:
            - containerPort: 5000 #port exposed as in dockerfile
              protocol: TCP
          env:
            - name: MODEL_REPO #environment variable from the dockerfile
              value: /usr/src/assignment1/models
      volumes:
        - name: model-repo
          persistentVolumeClaim: #claiming the persistent volume 
            claimName: nfs-model-repo
