apiVersion: v1
kind: Service
metadata:
  name: train-service
  labels:
    app: train
  namespace: bert_app
spec:
  type: LoadBalancer
  ports:
    - port: 5001
      targetPort: 5000
  selector:
    app: train