apiVersion: v1
kind: Service
metadata:
  name: train-service
  labels:
    app: train
  namespace: bertapp
spec:
  type: LoadBalancer #preferred for external acces
  ports:
    - port: 5001 #making sure the training can be started via port 5001
      targetPort: 5000 
  selector:
    app: train
