apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: train
  name: train
  namespace: bert_app
spec:
  replicas: 2 #hoeveel pods nodig?
  selector:
    matchLabels:
      app: train
  template:
    metadata:
      labels:
        app: train
    spec:
      containers:
        - name: train-api
          image: #gcp push
          volumeMounts:
            - mountPath: /usr/src/assignment1/models
              name: model-repo
          ports:
            - containerPort: 5000
              protocol: TCP
          env:
            - name: MODEL_REPO
              value: /usr/src/assignment1/models
            - name: DB_API
              value: http://dbAPI:5000/db/bert
      volumes:
        - name: model-repo
          persistentVolumeClaim:
            claimName: postgres-model-repo
