apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: train
  name: train
  namespace: bertapp
spec:
  replicas: 2 #hoeveel pods nodig?
  selector:
    matchLabels:
      app: train
  template:
    metadata:
      labels:
        app: train
    spec:
      containers:
        - name: train-api
          image: gcr.io/data-engineering2020/assignment1/train:0.0.1 #gcp push
          resources:
            requests:
              memory: "2Gi"
            limits:
              memory: "5Gi"
          volumeMounts:
            - mountPath: /usr/src/assignment1/models
              name: model-repo
          ports:
            - containerPort: 5000
              protocol: TCP
          env:
            - name: MODEL_REPO
              value: /usr/src/assignment1/models
            - name: DB_API
              value: http://dbAPI:5000/db/bert

      volumes:
        - name: model-repo
          persistentVolumeClaim:
            claimName: nfs-model-repo
